version: "3.8"
services:
  backend:
    env_file: .env
    container_name: backend
    hostname: backend
    build: 
      context: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      - ${API_KEY}
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 5s
      timeout: 5s
      retries: 3